### ISSUE TITLE
print out the smiles of the reactions

### ISSUE THREAD

**Issue by juditzador** [rubenvdvijver/PESViewer#1]
I added a small function called `reaction_smi` to print out the smiles of the reactions like this:

```
OOC[CH2] = [OH] + O=CC  0.00  21.45   -46.26
OOC[CH2] = [O]OCC  0.00  18.36   -19.18
OOC[CH2] = OCC[O]  0.00  24.55   -52.82
OOC[CH2] = [OH] + O1CC1  0.00  10.72   -16.11
OOC[CH2] = O[O] + C=C  0.00  11.03   -0.91
OOC[CH2] = OOC=C + [H]  0.00  34.31   31.43
```

```
        Given a list of transition states and barrierless channels
        write a reaction_smi.out file that contains the reactions as, e.g.:
        OOC[CH2] = [OH] + O1CC1i  0.0  10.72  -16.11
        The three numbers are the energy of the reactant, transition state and product.
        The barrier height for barrierless reactions is given as max(Ereact,Eprod)
```

**Comment by sthakris** [comment]
@juditzador I was using the pesviewer script though it plots the PES graph but as you said I do not get file reaction_smi.out listing the reactions as you mentioned. If there is an updated script can you please provide.
Thank you!

**Comment by juditzador** [comment]
@sthakris , please use the version in my repo: https://github.com/zadorlab/PESViewer

**Comment by sthakris** [comment]
@juditzador Thank you very much! 
I ran into another issue with updated script.
I was running the code from the repo you provided. It gives me synatx error in line 973 if I resolve that with comment it shows another at line 1044 in pesviewer.py. 

I am using python 2.7 for running this script as suugested.

**Comment by juditzador** [comment]
I will correct the readme, please use python 3.7 or similar.

**Comment by sthakris** [comment]
@juditzador Just to update, the script is working as intended. I used the python version 3.8. Thank you very much!. It is a nice feature you added.
